CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE CLIENTE(
CODIGO INT NOT NULL IDENTITY,
NOME VARCHAR(100) NOT NULL,
RG VARCHAR(30) NOT NULL,
CPF VARCHAR(30) NOT NULL,
DATA_NASC DATE NOT NULL,
IDADE INT NULL DEFAULT 18,
SEXO VARCHAR (1) NOT NULL,
PRIMARY KEY(CODIGO)
);

CREATE TABLE PRODUTO(
CODIGO INT NOT NULL IDENTITY,
QTD_PRODUTO INT NULL, 
MARCA VARCHAR(50) NOT NULL,
SITUACAO VARCHAR(20) NOT NULL,
MODELO VARCHAR(100) NOT NULL,
VALOR SMALLMONEY DEFAULT 800,
PRIMARY KEY (CODIGO)
);

CREATE TABLE ENDERECO(
CODIGO INT NOT NULL IDENTITY,
ID_CLIENTE INT NOT NULL,
CEP VARCHAR(50) NOT NULL, 
BARRIO VARCHAR(100) NOT NULL,
PRIMARY KEY(CODIGO),
CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(CODIGO)
);

CREATE TABLE CONTATO(
CODIGO INT NOT NULL IDENTITY,
ID_CLIENTE INT NOT NULL,
NUMERO VARCHAR(20) NOT NULL,
PRIMARY KEY(CODIGO),
CONSTRAINT FK_CLIENTE_CONTATO FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(CODIGO)
);

CREATE TABLE DEPENDENTE(
CODIGO INT NOT NULL IDENTITY,
ID_CLIENTE INT NOT NULL,
NOME VARCHAR(100) NOT NULL,
RG VARCHAR(30) NOT NULL,
CPF VARCHAR(30) NOT NULL,
SEXO VARCHAR(1) NOT NULL,
DATA_NASC DATE NOT NULL,
IDADE INT NULL DEFAULT 18,
PRIMARY KEY(CODIGO),
CONSTRAINT FK_CLIENTE_DEP FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(CODIGO)
);

CREATE TABLE VENDA(
CODIGO INT NOT NULL IDENTITY,
ID_CLIENTE INT NOT NULL,
ID_PRODUTO INT NOT NULL, 
DATA_VENDA DATE NULL DEFAULT GETDATE(),
DATA_SAIDA DATE NULL DEFAULT GETDATE(),
DESCONTO INT NULL,
PRIMARY KEY(CODIGO),
CONSTRAINT FK_CLIENTE_VENDA FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(CODIGO),
CONSTRAINT FK_PRODUTO_VENDA FOREIGN KEY(ID_PRODUTO)
REFERENCES PRODUTO(CODIGO)
);