CREATE DATABASE MARMITA01;

USE MARMITA01;

CREATE TABLE LOGIN(
	ID INT NOT NULL IDENTITY,
	EMAIL VARCHAR(255) NOT NULL,
	SENHA VARCHAR(255) NOT NULL, 
	PRIMARY KEY(ID)
);

CREATE TABLE CLIENTE(
	TELEFONE VARCHAR(255) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	PONTOREFERENCIA VARCHAR(255) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	PRIMARY KEY(TELEFONE)
);

CREATE TABLE EMPRESA(
	ID INT NOT NULL IDENTITY,
	NOME VARCHAR(255) NOT NULL,
	CNPJ VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(255) NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ENTREGADOR(
	ID INT NOT NULL IDENTITY,
	ID_EMPRESA INT NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	CPF VARCHAR(255) NOT NULL,
	RG VARCHAR(255) NOT NULL,
	CELULAR VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID),
	CONSTRAINT FK_EMPRESA_ENTREGADOR FOREIGN KEY(ID_EMPRESA)
	REFERENCES EMPRESA(ID)
);

CREATE TABLE PEDIDO(
	ID INT NOT NULL IDENTITY,
	TELEFONE_CLIENTE VARCHAR(255) NOT NULL,
	ID_ENTREGADOR INT NOT NULL,
	STATUS VARCHAR(255) NOT NULL,
	TAXA_ENTREGA VARCHAR(255) NOT NULL,
	DATA DATE NULL DEFAULT GETDATE(),
	PRIMARY KEY(ID),
	CONSTRAINT FK_TELEFONE_CLIENTE_PEDIDO FOREIGN KEY(TELEFONE_CLIENTE)
	REFERENCES CLIENTE(TELEFONE),
	CONSTRAINT FK_ENDTREGADOR_PEDIDO FOREIGN KEY(ID_ENTREGADOR)
	REFERENCES ENTREGADOR(ID)
);

CREATE TABLE MARMITA(
	ID INT NOT NULL IDENTITY,
	NOME VARCHAR(255) NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	TAMANHO VARCHAR(255) NOT NULL,
	VALOR VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ITEM_PEDIDO(
	ID_MARMITA INT NOT NULL,
	ID_PEDIDO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	CONSTRAINT FK_MARMITA_ITEM_PEDIDO FOREIGN KEY(ID_MARMITA)
	REFERENCES MARMITA(ID),
	CONSTRAINT FK_PEDIDO_ITEM_PEDIDO FOREIGN KEY(ID_PEDIDO)
	REFERENCES PEDIDO(ID)
);

INSERT INTO LOGIN(EMAIL, SENHA)
	VALUES('maria_lima.2@gmail.com', 'abacateverde')

INSERT INTO LOGIN(EMAIL, SENHA)
	VALUES('joazinho012@gmail.com', 'laranjaamrela')

INSERT INTO LOGIN(EMAIL, SENHA)
	VALUES('fabio_silva.lima@gmail.com', 'naoeminhasenha')

INSERT INTO LOGIN(EMAIL, SENHA)
	VALUES('carol_andarde@hotmai.com', 'limaoAzedo')

INSERT INTO LOGIN(EMAIL, SENHA)
	VALUES('julialima07@gmail.com', 'morangoVermelho')

SELECT * FROM LOGIN;

INSERT INTO CLIENTE(TELEFONE, NOME, ENDERECO, PONTOREFERENCIA, NASCIMENTO)
	VALUES('071996187642', 'MARIA LIMA', 'RUA DOS LIMOEIROS/NUMERO: 12', 'AO LADO DO COLEGIO DO LIMOEIRO', '02/09/1991')

INSERT INTO CLIENTE(TELEFONE, NOME, ENDERECO, PONTOREFERENCIA, NASCIMENTO)
	VALUES('071886282653', 'JOAO MIRANDA', 'RUA MÔNICA/NUMERO: 2', 'RUA DO POSTO SHELL', '14/08/2003')

INSERT INTO CLIENTE(TELEFONE, NOME, ENDERECO, PONTOREFERENCIA, NASCIMENTO)
	VALUES('719111002536', 'FABIO SILVA', 'RUA ALBERTO PONDE/NUMERO: 147', 'RUA DO SUN FLAT', '13/10/2000')

INSERT INTO CLIENTE(TELEFONE, NOME, ENDERECO, PONTOREFERENCIA, NASCIMENTO)
	VALUES('071986077905', 'CAROL ANDRADE', 'RUA B/NUMERO: 16', 'AO LADO DO MERCADO SEU JORGE', '23/11/1995')

INSERT INTO CLIENTE(TELEFONE, NOME, ENDERECO, PONTOREFERENCIA, NASCIMENTO)
	VALUES('071909087568', 'JULIA LIMA', 'RUA SÃO JOSÉ/NUMERO: 1', 'EM FRENTE AO COLEGIO MARIA DAS DORES', '12/02/1990')

SELECT * FROM CLIENTE;

INSERT INTO EMPRESA(NOME, CNPJ, EMAIL, TELEFONE, ENDERECO)
	VALUES('CANTINHO DAS MARMITAS', '88.535.056/0001-91', 'cantinhodasmarmitas@gmail.com', '(71) 96948-1423', 'RUA ACESSO SEIS/NUMERO: 15')

SELECT * FROM EMPRESA

INSERT INTO ENTREGADOR(ID_EMPRESA, NOME, CPF, RG, CELULAR)
	VALUES(1, 'MARIO', '208.236.780-08', '19.295.581-0', '(71) 98468-6836')

INSERT INTO ENTREGADOR(ID_EMPRESA, NOME, CPF, RG, CELULAR)
	VALUES(1, 'CARLOS', '675.459.330-01', '45.383.530-2', '(71) 99235-4519')

INSERT INTO ENTREGADOR(ID_EMPRESA, NOME, CPF, RG, CELULAR)
	VALUES(1, 'ALINE', '367.687.710-19', '41.988.586-9', '(71) 98971-5479')

SELECT * FROM ENTREGADOR

INSERT INTO MARMITA(NOME, DESCRICAO, TAMANHO, VALOR)
	VALUES('MAIS SABOR', 'ARROZ INTEGRAL + CARNE MOIDA + CENOURA RALADA + BRÓCOLIS REFOGADO', '350g', 'R$35,99')

INSERT INTO MARMITA(NOME, DESCRICAO, TAMANHO, VALOR)
	VALUES('QUE SABOR', 'GRÃO DE BICO + OMELETE COM TOMATE PICADO + PURÊ DE MANDIOQUINHA', '250g', 'R$25,99')

INSERT INTO MARMITA(NOME, DESCRICAO, TAMANHO, VALOR)
	VALUES('SABOREAR', 'MACARRÃO + FRANGO GRELHADO + SALADA DE BRÓCOLIS E TOMATE', '300g', 'R$27.99')

INSERT INTO MARMITA(NOME, DESCRICAO, TAMANHO, VALOR)
	VALUES('SANTA LEDA MARMITARIA',  'FAROFA DE BANANA + CARNE ASSADA + VINAGRETE', '500g', 'R$33.49')

SELECT * FROM MARMITA

INSERT INTO PEDIDO(TELEFONE_CLIENTE, ID_ENTREGADOR, STATUS, TAXA_ENTREGA, DATA)
	VALUES('071996187642', 4, 'EM ANDAMENTO', 'R$4.99', '15/04/2023')

INSERT INTO PEDIDO(TELEFONE_CLIENTE, ID_ENTREGADOR, STATUS, TAXA_ENTREGA, DATA)
	VALUES('719111002536', 2, 'ENTREGE', 'R$9.99', '28/03/2023') 

INSERT INTO PEDIDO(TELEFONE_CLIENTE, ID_ENTREGADOR, STATUS, TAXA_ENTREGA, DATA)
	VALUES('071909087568', 3, 'EM ANDAMENTO', 'R$7.99', '11/04/2023')

SELECT * FROM PEDIDO

INSERT INTO ITEM_PEDIDO(ID_MARMITA, ID_PEDIDO, QUANTIDADE)
	VALUES(1, 2, 1)

INSERT INTO ITEM_PEDIDO(ID_MARMITA, ID_PEDIDO, QUANTIDADE)
	VALUES(4, 1, 2)

INSERT INTO ITEM_PEDIDO(ID_MARMITA, ID_PEDIDO, QUANTIDADE)
	VALUES(2, 3, 2)

SELECT * FROM ITEM_PEDIDO

UPDATE CLIENTE
	SET NASCIMENTO = '02/10/1996'
	WHERE NOME = 'MARIA LIMA';

UPDATE CLIENTE
	SET NASCIMENTO = '18/07/2003'
	WHERE NOME = 'JULIA LIMA'

UPDATE MARMITA
	SET TAMANHO = '350g'
	WHERE ID = 2;

UPDATE MARMITA
	SET VALOR = 'R$R$39.99'
	WHERE ID = 1;

UPDATE MARMITA
	SET VALOR = 'R$25.99'
	WHERE ID = 2;

DELETE FROM CLIENTE
	WHERE NOME = 'JOAO MIRANDA';

DELETE FROM CLIENTE
	WHERE NOME = 'CAROL ANDRADE';

DELETE FROM MARMITA
	WHERE ID = 3;
