CREATE DATABASE MARMITA;

USE MARMITA;

CREATE TABLE LOGIN(
	ID INT NOT NULL IDENTITY,
	EMAIL VARCHAR(255) NOT NULL,
	SENHA VARCHAR(255) NOT NULL, 
	PRIMARY KEY(ID)
);

CREATE TABLE CLIENTE(
	TELEFONE VARCHAR(255) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	PONTOREFERENCIA VARCHAR(255) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	PRIMARY KEY(TELEFONE)
);

CREATE TABLE EMPRESA(
	ID INT NOT NULL IDENTITY,
	NOME VARCHAR(255) NOT NULL,
	CNPJ VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(255) NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ENTREGADOR(
	ID INT NOT NULL IDENTITY,
	ID_EMPRESA INT NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	CPF VARCHAR(255) NOT NULL,
	RG VARCHAR(255) NOT NULL,
	CELULAR VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID),
	CONSTRAINT FK_EMPRESA_ENTREGADOR FOREIGN KEY(ID_EMPRESA)
	REFERENCES EMPRESA(ID)
);

CREATE TABLE PEDIDO(
	ID INT NOT NULL IDENTITY,
	TELEFONE_CLIENTE VARCHAR(255) NOT NULL,
	ID_ENTREGADOR INT NOT NULL,
	STATUS VARCHAR(255) NOT NULL,
	TAXA_ENTREGA VARCHAR(255) NOT NULL,
	DATA DATE NULL DEFAULT GETDATE(),
	PRIMARY KEY(ID),
	CONSTRAINT FK_TELEFONE_CLIENTE_PEDIDO FOREIGN KEY(TELEFONE_CLIENTE)
	REFERENCES CLIENTE(TELEFONE),
	CONSTRAINT FK_ENDTREGADOR_PEDIDO FOREIGN KEY(ID_ENTREGADOR)
	REFERENCES ENTREGADOR(ID)
);

CREATE TABLE MARMITA(
	ID INT NOT NULL IDENTITY,
	NOME VARCHAR(255) NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	TAMANHO VARCHAR(255) NOT NULL,
	VALOR VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ITEM_PEDIDO(
	ID_MARMITA INT NOT NULL,
	ID_PEDIDO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	CONSTRAINT FK_MARMITA_ITEM_PEDIDO FOREIGN KEY(ID_MARMITA)
	REFERENCES MARMITA(ID),
	CONSTRAINT FK_PEDIDO_ITEM_PEDIDO FOREIGN KEY(ID_PEDIDO)
	REFERENCES PEDIDO(ID)
);
